---
title: "Generalized Linear Anchor Regression"
author: "Maic Rakitta"
date: "`r Sys.Date()`"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

This package was constructed in the scope of my master thesis submitted in fulfilment of the requirement for the Master of Science ETH in Applied Mathematics. The work described was conducted between September 2020 and February 2021, under the supervision of Professor P. L. Buehlmann, in the Department of Mathematics at ETH Zurich.

My thesis proposes Generalized Linear Anchor REgression (GLARE), which constitutes a generalisation of Anchor Regression (AR) by [Rothenhaeusler, Meinshausen, Buehlmann and Peters](https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/rssb.12398) to Generalised Linear Models (GLM).

For a short introduction to GLARE and an explanation of the application of the package, a vignette with a binomial example is provided in the package. If you have any questions, please do not hesitate to contact the author: rakittam@student.ethz.ch
